
services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  app1:
    build: .
    restart: unless-stopped
    environment:
      REDIS_HOST: redis
      PORT: "3000"
      INSTANCE_ID: rate-limiter-1
      DASHBOARD_ORIGIN: https://rateforge-dashboard-std17.vercel.app
    expose:
      - "3000"
    depends_on:
      redis:
        condition: service_healthy

  app2:
    build: .
    restart: unless-stopped
    environment:
      REDIS_HOST: redis
      PORT: "3000"
      INSTANCE_ID: rate-limiter-2
      DASHBOARD_ORIGIN: https://rateforge-dashboard-std17.vercel.app
    expose:
      - "3000"
    depends_on:
      redis:
        condition: service_healthy

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app1
      - app2

  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - nginx

volumes:
  caddy_data:
  caddy_config:

